from setuptools import setup

setup(
    name='sig_process_arrays',
    version='1.0',
    packages=['venv.Lib.site-packages.numpy', 'venv.Lib.site-packages.numpy.ma',
              'venv.Lib.site-packages.numpy.ma.tests', 'venv.Lib.site-packages.numpy.doc',
              'venv.Lib.site-packages.numpy.fft', 'venv.Lib.site-packages.numpy.fft.tests',
              'venv.Lib.site-packages.numpy.lib', 'venv.Lib.site-packages.numpy.lib.tests',
              'venv.Lib.site-packages.numpy.core', 'venv.Lib.site-packages.numpy.core.tests',
              'venv.Lib.site-packages.numpy.f2py', 'venv.Lib.site-packages.numpy.f2py.tests',
              'venv.Lib.site-packages.numpy.tests', 'venv.Lib.site-packages.numpy.compat',
              'venv.Lib.site-packages.numpy.compat.tests', 'venv.Lib.site-packages.numpy.linalg',
              'venv.Lib.site-packages.numpy.linalg.tests', 'venv.Lib.site-packages.numpy.random',
              'venv.Lib.site-packages.numpy.random.tests', 'venv.Lib.site-packages.numpy.testing',
              'venv.Lib.site-packages.numpy.testing.tests', 'venv.Lib.site-packages.numpy.testing._private',
              'venv.Lib.site-packages.numpy.distutils', 'venv.Lib.site-packages.numpy.distutils.tests',
              'venv.Lib.site-packages.numpy.distutils.command', 'venv.Lib.site-packages.numpy.distutils.fcompiler',
              'venv.Lib.site-packages.numpy.matrixlib', 'venv.Lib.site-packages.numpy.matrixlib.tests',
              'venv.Lib.site-packages.numpy.polynomial', 'venv.Lib.site-packages.numpy.polynomial.tests',
              'venv.Lib.site-packages.matplotlib', 'venv.Lib.site-packages.matplotlib.tri',
              'venv.Lib.site-packages.matplotlib.axes', 'venv.Lib.site-packages.matplotlib.cbook',
              'venv.Lib.site-packages.matplotlib.style', 'venv.Lib.site-packages.matplotlib.compat',
              'venv.Lib.site-packages.matplotlib.testing', 'venv.Lib.site-packages.matplotlib.testing.jpl_units',
              'venv.Lib.site-packages.matplotlib.backends', 'venv.Lib.site-packages.matplotlib.backends.qt_editor',
              'venv.Lib.site-packages.matplotlib.sphinxext', 'venv.Lib.site-packages.matplotlib.projections',
              'venv.Lib.site-packages.mpl_toolkits.mplot3d', 'venv.Lib.site-packages.mpl_toolkits.axes_grid',
              'venv.Lib.site-packages.mpl_toolkits.axes_grid1', 'venv.Lib.site-packages.mpl_toolkits.axisartist',
              'Arrays'],
    url='',
    license='Free',
    author='Sammy Kolpinizki',
    author_email='sammykol@gmail.com',
    description='Plots magnitude of beam response for 1D receiver arrays - This is a "Portfolio" exercise from the Udacity Nano Degree in Datasciene '
)
